name: lumiere_ui_example
description: Example of how to use the lumiere_ui package.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  lumiere_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
